title: "UniFicar PDF"
description: Merge PDF | Unir PDF
baseurl: ""
url: "https://unirpdf-73b.pages.dev"
liquid:
  error_mode: strict
author: RUPESH


# Multilingual settings
languages: ["en", "fr", "es", "pt", "th"]
default_lang: "es"

# Build settings
markdown: kramdown
theme: null
plugins:
  - jekyll-feed
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/
  - .bundle/
  - node_modules/

kramdown:
  auto_ids: true
  toc_levels: [2, 3]

# Custom permalinks per language folder
defaults:
  - scope:
      path: "_posts/es"
    values:
      lang: es
      permalink: /:title/

  - scope:
      path: "_posts/en"
    values:
      lang: en
      permalink: /en/:title/

  - scope:
      path: "_posts/fr"
    values:
      lang: fr
      permalink: /fr/:title/

  - scope:
      path: "_posts/pt"
    values:
      lang: pt
      permalink: /pt/:title/

  - scope:
      path: "_posts/th"
    values:
      lang: th
      permalink: /th/:title/

collections:
  en:
    output: true
  fr:
    output: true
  es:
    output: true
  pt:
    output: true
  th:
    output: true


include:
  - _headers
  - _redirects
  - 404.html

